version: '3'
services:
  kong:
    image: kong:1.4-ubuntu
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

  kong-dashboard:
    container_name: kong_dashboard
    image: pgbi/kong-dashboard
    command: start --kong-url http://kong:8001
    ports:
      - "8080:8080"
    depends_on:
      - kong

  backend:
    image: vad1mo/hello-world-rest
    ports:
      - "5050:5050"
